# params.yaml
index_col: 'flat_id'
target_col: 'price'
one_hot_drop: 'if_binary'
iterations: 1000
learning_rate: 0.1
depth: 6
loss_function: 'RMSE'
eval_metric: 'RMSE'
random_seed: 42
n_splits: 5
metrics: ['neg_mean_absolute_error', 'neg_root_mean_squared_error', 'r2', 'neg_mean_absolute_percentage_error']
n_jobs: -1 
retrain: True
autostage: True